sudo: required
services:
  - docker

before_install:
  - docker build -t cloves/docker-react-estudos -f Dockerfile.dev .

script:
  - docker run cloves/docker-react-estudos npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-estudos"
  env: "DockerEstudos-env"
  bucket_name: "elasticbeanstalk-us-east-2-217404719255"
  bucket_path: "docker-estudos"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
