sudo: required
services:
  - docker

before_install:
  - docker build -t cloves/docker-react-estudos -f Dockerfile.dev .

script:
  - docker run cloves/docker-react-estudos npm run test -- --coverage
